try_except = open("try_except.py", "r")
for lines in try_except:
    print(lines)
try_except.close()